This is an unofficial typst template for writing a report or thesis in ETH Zurich's Computer Security research lab (COMSEC). One can adapt it to other thesis projects too.

** Usage
#+begin_src bash
git clone https://github.com/spherinder/ethz-infk-thesis.git
cd ethz-infk-thesis
typst watch --root . src/main.typ
#+end_src

Now open ~src/main.pdf~ in your favorite pdf viewer, and make changes to the file structure.

** File structure
#+begin_src
.
├── assets                          // Images, CSV-Files, etc.
│   └── header-image.svg            // Banner on the cover page
├── chapters                        // Content
│   ├── 01-Introduction.typ
│   ├── ...
│
├── dependencies.typ                // Project dependencies
├── abbreviations.typ               // Abbreviations and glossary
├── bibliography.bib                // Bibliography (e.g. generated by Zotero + Better BibTex)
└── main.typ                        // Thesis template
#+end_src

** Fonts
This template requires your system to have these two fonts installed:
- New Computer Modern
- New Computer Modern Sans

*** NixOS
In your ~configuration.nix~:
#+begin_src nix
fonts.packages = with pkgs; [
liberation_ttf # here are your other fonts (liberation is just an example)
texlivePackages.newcomputermodern # ← New Computer Modern font
]
#+end_src

# ** Development
# In case you want to contribute, check out the repo into a [typst package directory](https://github.com/typst/packages?tab=readme-ov-file#local-packages)

# *** Example for Linux:
# Local package path: `~/.local/share/typst/packages/local/optimal-ovgu-thesis/0.1.0`

# ```sh
# mkdir -p ~/.local/share/typst/packages/local/optimal-ovgu-thesis
# cd ~/.local/share/typst/packages/local/optimal-ovgu-thesis
# git clone git@github.com:v411e/optimal-ovgu-thesis.git
# mv optimal-ovgu-thesis 0.1.0
# ```

# This will make the package available locally, so you can use `typst init "@local/optimal-ovgu-thesis:0.1.0"` to create a test-project from the template.
